# Generated by Django 4.2.4 on 2023-11-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room'},
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
